export type PaymentMode = 'UPI' | 'IMPS' | 'NEFT' | 'RTGS';

export type VoucherStatus = 'Success' | 'Pending' | 'Failed';

export type TallySyncStatus = 'Synced' | 'Pending' | 'Failed' | 'In Progress';

export type WorkflowStage =
  | 'Payment Request'
  | 'Voucher Created'
  | 'Bank Transfer'
  | 'Verification'
  | 'Tally Sync'
  | 'Completed';

export interface DirectPayment {
  id: string;
  tripRefNo: string;
  costCenter: string;
  paymentMode: PaymentMode;
  fromBank: string;
  refNo: string;
  requestDate: string;
  transactionDate: string;
  transferred: boolean;
  amount: number;
  beneficiary: string;
  status: VoucherStatus;
  voucherNo: string;
}

export interface TransactionLine {
  id: string;
  ledgerName: string;
  debit: number;
  credit: number;
  narration: string;
}

export interface Voucher {
  id: string;
  voucherBranch: string;
  voucherNo: string;
  voucherDate: string;
  voucherType: string;
  financialYear: string;
  refType: string;
  referenceNo: string;
  paymentMode: PaymentMode;
  chequeNeftNo: string;
  autoGenerated: boolean;
  statusRemarks: string;
  rejectRemarks: string;
  tallySyncStatus: TallySyncStatus;
  status: VoucherStatus;
  currentStage: WorkflowStage;
  transactions: TransactionLine[];
}

export interface TallySyncRecord {
  id: string;
  voucherNo: string;
  voucherDate: string;
  branch: string;
  tallySyncStatus: TallySyncStatus;
  syncedAt: string;
  errorMessage: string;
  retryCount: number;
}
